# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa8b7f5531d9ad4fc18d38da8d720ff76ad3ab51a09b64a7357109bc65df9066881e914e8f2f9a66446f9e64fd2e9d90c4cefea92b147b0ffed4d52a78f809be

test:
  secret_key_base: 73334699930fec6df23d1414e56c1e0c1ed93b8438aaff0aaa727d6b4d7b41ba99b5ec2c6bbd0d0076008543002f34f74e93eefd2c31f11b64c9600f28b0139b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
